sudo: required

language: ruby

services:
  - docker

before_install:
- docker build -t demiusen/sinatra .
- docker run -d -p 127.0.0.1:80:4567 demiusen/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run demiusen/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push demiusen/sinatra
